"""Relational model for the driver income / fleet finance system.

Design rules that this file follows:

* No dashboard KPI is stored. Totals, margins and ratios are computed by the
  aggregation services in ``apps.fleet.services`` using ORM aggregation.
* The two exceptions are ``DailyEarning.total_income`` and
  ``PayrollSettlement.balance``. These are *row-level* derived values, not KPIs,
  and they are database-generated columns so that the database — not Python and
  never JavaScript — is the single source of truth. They can also be filtered,
  ordered and aggregated on directly.
* All money is ``Decimal`` with two decimal places.
"""

from __future__ import annotations

from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F

ZERO = Decimal("0.00")


def money_field(**kwargs) -> models.DecimalField:
    """A consistent money column: 12 digits, 2 decimals, non-negative."""
    kwargs.setdefault("max_digits", 12)
    kwargs.setdefault("decimal_places", 2)
    kwargs.setdefault("default", ZERO)
    kwargs.setdefault("validators", [MinValueValidator(ZERO)])
    return models.DecimalField(**kwargs)


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# ---------------------------------------------------------------------------
# Core entities
# ---------------------------------------------------------------------------


class Driver(TimeStampedModel):
    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        INACTIVE = "inactive", "Inactive"
        ON_LEAVE = "on_leave", "On leave"

    name = models.CharField(max_length=150)
    phone = models.CharField(max_length=30, blank=True)
    email = models.EmailField(blank=True)
    license_number = models.CharField(max_length=60, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    joined_at = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ["name"]
        indexes = [models.Index(fields=["status"])]

    def __str__(self) -> str:
        return self.name


class Vehicle(TimeStampedModel):
    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        INACTIVE = "inactive", "Inactive"
        MAINTENANCE = "maintenance", "Maintenance"

    make = models.CharField(max_length=80)
    model = models.CharField(max_length=100)
    plate_number = models.CharField(max_length=30, unique=True)
    year = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    assigned_driver = models.ForeignKey(
        Driver,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="vehicles",
    )
    monthly_rent = money_field(
        help_text="Optional fixed monthly cost of holding the vehicle.",
    )
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ["make", "model", "plate_number"]
        indexes = [models.Index(fields=["status"])]

    @property
    def display_name(self) -> str:
        return f"{self.make} {self.model}"

    def __str__(self) -> str:
        return f"{self.make} {self.model} - {self.plate_number}"


class DailyEarning(TimeStampedModel):
    """One driver + vehicle + day of platform income.

    ``total_income`` is generated by the database as the sum of the platform
    columns, so an imported spreadsheet TOTAL can never disagree with its parts.
    """

    date = models.DateField()
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, related_name="daily_earnings")
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, related_name="daily_earnings")

    careem = money_field()
    uber = money_field()
    bolt = money_field()
    yango = money_field()
    cash = money_field()

    total_income = models.GeneratedField(
        expression=F("careem") + F("uber") + F("bolt") + F("yango") + F("cash"),
        output_field=models.DecimalField(max_digits=14, decimal_places=2),
        db_persist=True,
    )

    notes = models.TextField(blank=True)
    source_batch = models.ForeignKey(
        "ImportBatch",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="earnings",
    )

    class Meta:
        ordering = ["-date", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["date", "driver", "vehicle"],
                name="unique_daily_driver_vehicle",
            )
        ]
        indexes = [
            models.Index(fields=["date"]),
            models.Index(fields=["driver", "date"]),
            models.Index(fields=["vehicle", "date"]),
        ]

    @property
    def platform_breakdown(self) -> dict[str, Decimal]:
        return {name: getattr(self, name) for name in settings.INCOME_PLATFORMS}

    @property
    def is_active_day(self) -> bool:
        """An earning day only counts as active when income was actually made."""
        return (self.total_income or ZERO) > ZERO

    def __str__(self) -> str:
        return f"{self.date} - {self.driver} - {self.vehicle}"


class Expense(TimeStampedModel):
    """Operating expenses only. Driver pay lives in PayrollSettlement."""

    class Category(models.TextChoices):
        FUEL = "fuel", "Fuel"
        SALIK = "salik", "Salik"
        UBER_TRIPS = "uber_trips", "Uber Trips"
        WASHING = "washing", "Washing"
        SERVICE = "service", "Service"
        CAR_WASH = "car_wash", "Car Wash"
        OTHER = "other", "Other"

    class PaymentMethod(models.TextChoices):
        CASH = "cash", "Cash"
        CARD = "card", "Card"
        TRANSFER = "transfer", "Transfer"
        OTHER = "other", "Other"

    #: Categories treated as vehicle upkeep in the vehicle report.
    MAINTENANCE_CATEGORIES = ("service", "washing", "car_wash")

    date = models.DateField()
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, related_name="expenses")
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, related_name="expenses")
    category = models.CharField(max_length=30, choices=Category.choices)
    amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(ZERO)],
    )
    payment_method = models.CharField(
        max_length=20, choices=PaymentMethod.choices, default=PaymentMethod.CASH
    )
    description = models.CharField(max_length=255, blank=True)
    reference = models.CharField(max_length=100, blank=True)
    notes = models.TextField(blank=True)
    source_batch = models.ForeignKey(
        "ImportBatch",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="expenses",
    )

    class Meta:
        ordering = ["-date", "-id"]
        indexes = [
            models.Index(fields=["date"]),
            models.Index(fields=["driver", "date"]),
            models.Index(fields=["vehicle", "date"]),
            models.Index(fields=["category", "date"]),
        ]

    def __str__(self) -> str:
        return f"{self.date} - {self.category} - {self.amount}"


class PayrollSettlement(TimeStampedModel):
    """Monthly driver settlement, kept strictly separate from operating expenses.

    Settlement formula (explicit, and generated by the database)::

        balance = salary - advance - other_deductions - rent - paid_amount

    A positive balance is still owed to the driver; a negative balance means the
    driver has been overpaid for the period.
    """

    driver = models.ForeignKey(
        Driver, on_delete=models.CASCADE, related_name="payroll_settlements"
    )
    # Always stored as the first day of the settlement month.
    period = models.DateField(help_text="First day of the settlement month.")

    salary = money_field()
    advance = money_field()
    other_deductions = money_field()
    rent = money_field(help_text="Vehicle rent or similar recurring deduction.")
    paid_amount = money_field()

    balance = models.GeneratedField(
        expression=F("salary")
        - F("advance")
        - F("other_deductions")
        - F("rent")
        - F("paid_amount"),
        output_field=models.DecimalField(max_digits=14, decimal_places=2),
        db_persist=True,
    )

    notes = models.TextField(blank=True)

    class Meta:
        ordering = ["-period", "driver"]
        constraints = [
            models.UniqueConstraint(
                fields=["driver", "period"],
                name="unique_driver_payroll_period",
            )
        ]
        indexes = [
            models.Index(fields=["period"]),
            models.Index(fields=["driver", "period"]),
        ]

    @property
    def total_deductions(self) -> Decimal:
        return self.advance + self.other_deductions + self.rent

    def __str__(self) -> str:
        return f"{self.driver} - {self.period:%Y-%m}"


# ---------------------------------------------------------------------------
# Import pipeline
# ---------------------------------------------------------------------------


class ImportBatch(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        COMPLETED = "completed", "Completed"
        FAILED = "failed", "Failed"
        PARTIAL = "partial", "Partial"

    filename = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    total_rows = models.PositiveIntegerField(default=0)
    imported_rows = models.PositiveIntegerField(default=0)
    updated_rows = models.PositiveIntegerField(default=0)
    skipped_rows = models.PositiveIntegerField(default=0)
    failed_rows = models.PositiveIntegerField(default=0)
    error_message = models.TextField(blank=True)
    column_mapping = models.JSONField(default=dict, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="import_batches",
    )

    class Meta:
        ordering = ["-created_at", "-id"]
        verbose_name_plural = "import batches"

    def __str__(self) -> str:
        return f"{self.filename} - {self.status}"


class ImportRowIssue(models.Model):
    """One validation problem found on one spreadsheet row."""

    class Level(models.TextChoices):
        ERROR = "error", "Error"
        WARNING = "warning", "Warning"

    batch = models.ForeignKey(ImportBatch, on_delete=models.CASCADE, related_name="issues")
    row_number = models.PositiveIntegerField()
    column = models.CharField(max_length=100, blank=True)
    level = models.CharField(max_length=10, choices=Level.choices, default=Level.ERROR)
    code = models.CharField(max_length=50, blank=True)
    message = models.TextField()

    class Meta:
        ordering = ["row_number", "id"]

    def __str__(self) -> str:
        return f"row {self.row_number}: {self.message}"


# ---------------------------------------------------------------------------
# Audit trail
# ---------------------------------------------------------------------------


class AuditLog(models.Model):
    """Append-only record of who changed which financial object, and when."""

    class Action(models.TextChoices):
        CREATE = "create", "Create"
        UPDATE = "update", "Update"
        DELETE = "delete", "Delete"
        IMPORT = "import", "Import"

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="fleet_audit_logs",
    )
    action = models.CharField(max_length=20, choices=Action.choices)
    model_name = models.CharField(max_length=80)
    object_id = models.CharField(max_length=40, blank=True)
    object_label = models.CharField(max_length=255, blank=True)
    changes = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at", "-id"]
        indexes = [
            models.Index(fields=["model_name", "object_id"]),
            models.Index(fields=["-created_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.action} {self.model_name}#{self.object_id}"
