from __future__ import annotations

from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from rest_framework import serializers

from .models import (
    AuditLog,
    DailyEarning,
    Driver,
    Expense,
    ImportBatch,
    ImportRowIssue,
    PayrollSettlement,
    Vehicle,
)
from .services.money import ZERO, pct, quantize
from .services.periods import first_of_month

User = get_user_model()


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ["id", "username", "first_name", "last_name", "email", "is_staff", "is_superuser"]
        read_only_fields = fields


# ---------------------------------------------------------------------------
# Driver / Vehicle
# ---------------------------------------------------------------------------


class VehicleBriefSerializer(serializers.ModelSerializer):
    display_name = serializers.CharField(read_only=True)

    class Meta:
        model = Vehicle
        fields = ["id", "make", "model", "plate_number", "display_name", "status"]


class DriverBriefSerializer(serializers.ModelSerializer):
    class Meta:
        model = Driver
        fields = ["id", "name", "status"]


class DriverSerializer(serializers.ModelSerializer):
    vehicles = VehicleBriefSerializer(many=True, read_only=True)
    status_label = serializers.CharField(source="get_status_display", read_only=True)

    class Meta:
        model = Driver
        fields = [
            "id", "name", "phone", "email", "license_number",
            "status", "status_label", "joined_at", "notes",
            "vehicles", "created_at", "updated_at",
        ]
        read_only_fields = ["created_at", "updated_at"]

    def validate_name(self, value: str) -> str:
        value = value.strip()
        if not value:
            raise serializers.ValidationError("Name cannot be blank.")
        return value


class VehicleSerializer(serializers.ModelSerializer):
    assigned_driver_detail = DriverBriefSerializer(source="assigned_driver", read_only=True)
    display_name = serializers.CharField(read_only=True)
    status_label = serializers.CharField(source="get_status_display", read_only=True)

    class Meta:
        model = Vehicle
        fields = [
            "id", "make", "model", "display_name", "plate_number", "year",
            "status", "status_label", "assigned_driver", "assigned_driver_detail",
            "monthly_rent", "notes", "created_at", "updated_at",
        ]
        read_only_fields = ["created_at", "updated_at"]

    def validate_plate_number(self, value: str) -> str:
        return value.strip().upper()


# ---------------------------------------------------------------------------
# Daily earnings
# ---------------------------------------------------------------------------


class DailyEarningSerializer(serializers.ModelSerializer):
    driver_name = serializers.CharField(source="driver.name", read_only=True)
    vehicle_name = serializers.SerializerMethodField()
    vehicle_plate = serializers.CharField(source="vehicle.plate_number", read_only=True)
    total_income = serializers.DecimalField(
        max_digits=14, decimal_places=2, read_only=True,
        help_text="Generated by the database as the sum of the platform columns, cash included.",
    )
    platform_income = serializers.SerializerMethodField(
        help_text="The same total with cash taken out. Cash is not counted as income by default.",
    )
    status = serializers.SerializerMethodField()
    platform_shares = serializers.SerializerMethodField()

    class Meta:
        model = DailyEarning
        fields = [
            "id", "date", "driver", "driver_name", "vehicle", "vehicle_name", "vehicle_plate",
            *settings.INCOME_PLATFORMS,
            "total_income", "platform_income", "platform_shares", "status", "notes",
            "source_batch", "created_at", "updated_at",
        ]
        read_only_fields = [
            "total_income", "platform_income", "source_batch", "created_at", "updated_at",
        ]

    def get_vehicle_name(self, obj) -> str:
        return str(obj.vehicle)

    def get_platform_income(self, obj) -> Decimal:
        return quantize((obj.total_income or ZERO) - (obj.cash or ZERO))

    def get_status(self, obj) -> str:
        """Whether any money at all was recorded, cash included.

        This answers "did someone fill this row in", which is a different
        question from "does this row count towards income" - so it stays fixed
        while the cash toggle moves. A row that is pure cash is recorded, not
        missing.
        """
        return "recorded" if (obj.total_income or ZERO) > 0 else "no_income"

    def get_platform_shares(self, obj) -> dict:
        total = obj.total_income or ZERO
        return {name: pct(getattr(obj, name), total) for name in settings.INCOME_PLATFORMS}

    def validate(self, attrs):
        instance = self.instance
        date = attrs.get("date", getattr(instance, "date", None))
        driver = attrs.get("driver", getattr(instance, "driver", None))
        vehicle = attrs.get("vehicle", getattr(instance, "vehicle", None))

        if date and driver and vehicle:
            clash = DailyEarning.objects.filter(date=date, driver=driver, vehicle=vehicle)
            if instance:
                clash = clash.exclude(pk=instance.pk)
            if clash.exists():
                raise serializers.ValidationError(
                    {"date": "An entry already exists for this date, driver and vehicle."}
                )

        if vehicle and driver and vehicle.assigned_driver_id and vehicle.assigned_driver_id != driver.id:
            # Not fatal — fleets do swap cars — but the client should know.
            self.context.setdefault("warnings", []).append(
                f"{vehicle} is assigned to {vehicle.assigned_driver}, not {driver}."
            )
        return attrs


class DailyEarningWriteSerializer(DailyEarningSerializer):
    """Same rules; kept as a distinct name for clarity in the viewset."""


class DuplicateDaySerializer(serializers.Serializer):
    source_date = serializers.DateField(required=False, allow_null=True)
    target_date = serializers.DateField()
    driver = serializers.PrimaryKeyRelatedField(queryset=Driver.objects.all())
    vehicle = serializers.PrimaryKeyRelatedField(queryset=Vehicle.objects.all())
    overwrite = serializers.BooleanField(default=False)


# ---------------------------------------------------------------------------
# Expenses
# ---------------------------------------------------------------------------


class ExpenseSerializer(serializers.ModelSerializer):
    driver_name = serializers.CharField(source="driver.name", read_only=True)
    vehicle_name = serializers.SerializerMethodField()
    category_label = serializers.CharField(source="get_category_display", read_only=True)
    payment_method_label = serializers.CharField(
        source="get_payment_method_display", read_only=True
    )

    class Meta:
        model = Expense
        fields = [
            "id", "date", "driver", "driver_name", "vehicle", "vehicle_name",
            "category", "category_label", "amount",
            "payment_method", "payment_method_label",
            "description", "reference", "notes",
            "source_batch", "created_at", "updated_at",
        ]
        read_only_fields = ["source_batch", "created_at", "updated_at"]

    def get_vehicle_name(self, obj) -> str:
        return str(obj.vehicle)

    def validate_amount(self, value: Decimal) -> Decimal:
        if value < 0:
            raise serializers.ValidationError("Amount cannot be negative.")
        return quantize(value)


# ---------------------------------------------------------------------------
# Payroll
# ---------------------------------------------------------------------------


class PayrollSettlementSerializer(serializers.ModelSerializer):
    driver_name = serializers.CharField(source="driver.name", read_only=True)
    balance = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    total_deductions = serializers.DecimalField(
        max_digits=14, decimal_places=2, read_only=True
    )
    period_label = serializers.SerializerMethodField()
    formula = serializers.SerializerMethodField()

    class Meta:
        model = PayrollSettlement
        fields = [
            "id", "driver", "driver_name", "period", "period_label",
            "salary", "advance", "other_deductions", "rent", "paid_amount",
            "total_deductions", "balance", "formula", "notes",
            "created_at", "updated_at",
        ]
        read_only_fields = ["balance", "created_at", "updated_at"]

    def get_period_label(self, obj) -> str:
        return obj.period.strftime("%B %Y")

    def get_formula(self, obj) -> str:
        return "balance = salary − advance − other_deductions − rent − paid_amount"

    def validate_period(self, value):
        # Always normalise to the first day of the month.
        return first_of_month(value)


# ---------------------------------------------------------------------------
# Imports / audit
# ---------------------------------------------------------------------------


class ImportRowIssueSerializer(serializers.ModelSerializer):
    class Meta:
        model = ImportRowIssue
        fields = ["id", "row_number", "column", "level", "code", "message"]


class ImportBatchSerializer(serializers.ModelSerializer):
    issues = ImportRowIssueSerializer(many=True, read_only=True)
    created_by_username = serializers.CharField(
        source="created_by.username", read_only=True, default=None
    )

    class Meta:
        model = ImportBatch
        fields = [
            "id", "filename", "status", "total_rows", "imported_rows", "updated_rows",
            "skipped_rows", "failed_rows", "error_message", "column_mapping",
            "created_by", "created_by_username", "created_at", "issues",
        ]


class ImportBatchListSerializer(serializers.ModelSerializer):
    class Meta:
        model = ImportBatch
        fields = [
            "id", "filename", "status", "total_rows", "imported_rows", "updated_rows",
            "skipped_rows", "failed_rows", "created_at",
        ]


class ImportUploadSerializer(serializers.Serializer):
    file = serializers.FileField()
    driver = serializers.PrimaryKeyRelatedField(
        queryset=Driver.objects.all(), required=False, allow_null=True,
        help_text="Fallback driver when the file has no driver column.",
    )
    vehicle = serializers.PrimaryKeyRelatedField(
        queryset=Vehicle.objects.all(), required=False, allow_null=True,
        help_text="Fallback vehicle when the file has no vehicle column.",
    )
    skip_invalid = serializers.BooleanField(default=True)
    update_existing = serializers.BooleanField(default=True)
    create_expenses = serializers.BooleanField(default=True)


class AuditLogSerializer(serializers.ModelSerializer):
    actor_username = serializers.CharField(
        source="actor.username", read_only=True, default=None
    )

    class Meta:
        model = AuditLog
        fields = [
            "id", "actor", "actor_username", "action", "model_name",
            "object_id", "object_label", "changes", "created_at",
        ]
