'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, Download, FileText } from 'lucide-react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { scopeQuery, type ScopeState } from '@/lib/scope'
import type { Report, ReportDescriptor } from '@/lib/types'
import { fmtCell, fmtMoney, fmtNumber, fmtPercent } from '@/lib/format'
import { Async, EmptyState, PageIntro, Panel } from '@/components/ui/kit'

export function ReportsPage({ scope }: { scope: ScopeState }) {
  const [openKey, setOpenKey] = useState<string | null>(null)
  const catalogue = useApi(() => api.reportCatalogue(), [])

  if (openKey) {
    return <ReportDetail reportKey={openKey} scope={scope} onBack={() => setOpenKey(null)} />
  }

  return (
    <div className="animate-in fade-in duration-300">
      <PageIntro
        eyebrow="Workspace / Reports"
        title="Reports"
        description="Every report is generated by the backend for the period you selected above."
      />
      <Async query={catalogue} loadingLabel="Loading report catalogue…">
        {(data) =>
          data.reports.length === 0 ? (
            <Panel>
              <EmptyState title="No reports available" />
            </Panel>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {data.reports.map((report: ReportDescriptor) => (
                <ReportCard
                  key={report.key}
                  report={report}
                  scope={scope}
                  onOpen={() => setOpenKey(report.key)}
                />
              ))}
            </div>
          )
        }
      </Async>
    </div>
  )
}

function ReportCard({
  report,
  scope,
  onOpen,
}: {
  report: ReportDescriptor
  scope: ScopeState
  onOpen: () => void
}) {
  const query = useMemo(() => scopeQuery(scope), [scope])
  const detail = useApi<Report>(() => api.report(report.key, query), [report.key, JSON.stringify(query)])
  const headline = detail.data?.kpis?.[0]

  return (
    <div className="flex flex-col rounded-xl border border-border/70 bg-card p-5 shadow-sm">
      <div className="mb-5 flex size-10 items-center justify-center rounded-xl bg-[#55cfa4]/15 text-[#299b78]">
        <FileText className="size-5" />
      </div>
      <h3 className="text-[14px] font-semibold">{report.title}</h3>
      <p className="mt-1 flex-1 text-[11px] leading-relaxed text-muted-foreground">
        {report.description}
      </p>
      <div className="mt-5 flex items-end justify-between gap-2">
        <div>
          <span className="font-mono text-[18px] font-semibold">
            {detail.initialLoading
              ? '…'
              : detail.error
                ? 'N/A'
                : headline
                  ? headline.format === 'percent'
                    ? fmtPercent(headline.value)
                    : headline.format === 'number'
                      ? fmtNumber(headline.value)
                      : fmtMoney(headline.value, detail.data?.currency)
                  : fmtNumber(detail.data?.row_count ?? null)}
          </span>
          {headline && (
            <p className="mt-0.5 text-[10px] text-muted-foreground">{headline.label}</p>
          )}
        </div>
        <button onClick={onOpen} className="text-[11px] font-semibold text-[#299b78]">
          Open report →
        </button>
      </div>
    </div>
  )
}

export function ReportDetail({
  reportKey,
  scope,
  onBack,
}: {
  reportKey: string
  scope: ScopeState
  onBack: () => void
}) {
  const query = useMemo(() => scopeQuery(scope), [scope])
  const report = useApi<Report>(() => api.report(reportKey, query), [reportKey, JSON.stringify(query)])

  return (
    <div className="animate-in fade-in duration-300">
      <button
        onClick={onBack}
        className="mb-3 flex items-center gap-1 text-[11px] font-medium text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="size-3.5" />
        Back to reports
      </button>
      <Async query={report} loadingLabel="Building report…">
        {(data) => (
          <>
            <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
              <div>
                <h2 className="text-[28px] font-semibold tracking-[-0.04em]">{data.title}</h2>
                <p className="mt-1 text-[12px] text-muted-foreground">{data.description}</p>
                <p className="mt-1 text-[11px] text-muted-foreground">
                  {data.scope.period.label} · {data.scope.period.start} → {data.scope.period.end}
                </p>
              </div>
              <button
                onClick={() => void api.reportCsv(reportKey, query)}
                className="flex items-center gap-2 rounded-lg bg-[#1f3337] px-4 py-2.5 text-[11px] font-medium text-white"
              >
                <Download className="size-3.5" />
                Export CSV
              </button>
            </div>

            {data.kpis.length > 0 && (
              <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                {data.kpis.map((kpi) => (
                  <div
                    key={kpi.label}
                    className="rounded-xl border border-border/70 bg-card p-4 shadow-sm"
                  >
                    <p className="text-[11px] font-medium text-muted-foreground">{kpi.label}</p>
                    <p className="mt-2 font-mono text-[21px] font-semibold">
                      {fmtCell(kpi.value, kpi.format, data.currency)}
                    </p>
                    {kpi.note && (
                      <p className="mt-1 text-[10px] text-muted-foreground">{kpi.note}</p>
                    )}
                  </div>
                ))}
              </div>
            )}

            {data.notes && (
              <p className="mb-5 rounded-lg border border-border bg-muted/40 px-4 py-3 text-[11px] text-muted-foreground">
                {data.notes}
              </p>
            )}

            <Panel
              title={`${data.row_count.toLocaleString('en-US')} rows`}
              description="Straight from the report service — no client-side maths."
            >
              {data.rows.length === 0 ? (
                <EmptyState
                  title="This report has no rows for the selected period"
                  description="Widen the period or pick a different scope."
                />
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[720px] text-left">
                    <thead className="bg-muted/40 text-[10px] uppercase tracking-wider text-muted-foreground">
                      <tr>
                        {data.columns.map((column) => (
                          <th
                            key={column.key}
                            className={`px-5 py-3 font-semibold ${column.format !== 'text' ? 'text-right' : ''}`}
                          >
                            {column.label}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {data.rows.map((row, index) => (
                        <tr key={index} className="text-[11px] hover:bg-muted/30">
                          {data.columns.map((column) => (
                            <td
                              key={column.key}
                              className={`px-5 py-3 ${
                                column.format !== 'text' ? 'text-right font-mono' : ''
                              }`}
                            >
                              {fmtCell(row[column.key], column.format, data.currency)}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                    {data.totals && (
                      <tfoot className="border-t-2 border-border bg-muted/40 text-[11px] font-semibold">
                        <tr>
                          {data.columns.map((column, index) => (
                            <td
                              key={column.key}
                              className={`px-5 py-3 ${
                                column.format !== 'text' ? 'text-right font-mono' : ''
                              }`}
                            >
                              {index === 0
                                ? 'Total'
                                : column.key in (data.totals ?? {})
                                  ? fmtCell(data.totals![column.key], column.format, data.currency)
                                  : ''}
                            </td>
                          ))}
                        </tr>
                      </tfoot>
                    )}
                  </table>
                </div>
              )}
            </Panel>
          </>
        )}
      </Async>
    </div>
  )
}
